# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ConvertCoinUI.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ConversorDeMoeda(object):
    def setupUi(self, ConversorDeMoeda):
        ConversorDeMoeda.setObjectName("ConversorDeMoeda")
        ConversorDeMoeda.resize(821, 532)
        ConversorDeMoeda.setMinimumSize(QtCore.QSize(805, 532))
        ConversorDeMoeda.setMaximumSize(QtCore.QSize(821, 532))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons and Images/Logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        ConversorDeMoeda.setWindowIcon(icon)
        ConversorDeMoeda.setIconSize(QtCore.QSize(50, 50))
        self.TelaConv = QtWidgets.QWidget(ConversorDeMoeda)
        self.TelaConv.setObjectName("TelaConv")
        self.line_valor = QtWidgets.QLineEdit(self.TelaConv)
        self.line_valor.setGeometry(QtCore.QRect(90, 310, 271, 51))
        self.line_valor.setStyleSheet("background-color: rgba(0, 0 , 0, 0);\n"
"border: 2px solid rgba(0,0,0,0);\n"
"border-bottom-color: #A9ACF9;\n"
"color: rgb(0,0,0);\n"
"padding-bottom: 8px;\n"
"border-radius: 0px;\n"
"font: 10pt \"Montserrat\";")
        self.line_valor.setText("")
        self.line_valor.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.line_valor.setClearButtonEnabled(False)
        self.line_valor.setObjectName("line_valor")
        self.simbolo_inicial = QtWidgets.QLabel(self.TelaConv)
        self.simbolo_inicial.setGeometry(QtCore.QRect(80, 370, 71, 111))
        self.simbolo_inicial.setStyleSheet("font: 25 50pt \"Corbel Light\";\n"
"color: #A9ACF9;")
        self.simbolo_inicial.setObjectName("simbolo_inicial")
        self.lbl_de = QtWidgets.QLabel(self.TelaConv)
        self.lbl_de.setGeometry(QtCore.QRect(380, 340, 31, 21))
        self.lbl_de.setStyleSheet("font: 25 20pt \"Corbel Light\";\n"
"color: #A9ACF9;")
        self.lbl_de.setObjectName("lbl_de")
        self.lbl_para = QtWidgets.QLabel(self.TelaConv)
        self.lbl_para.setGeometry(QtCore.QRect(550, 340, 61, 21))
        self.lbl_para.setStyleSheet("font: 25 20pt \"Corbel Light\";\n"
"color: #A9ACF9;")
        self.lbl_para.setObjectName("lbl_para")
        self.conv_cambio = QtWidgets.QComboBox(self.TelaConv)
        self.conv_cambio.setGeometry(QtCore.QRect(610, 340, 121, 22))
        self.conv_cambio.setEditable(False)
        self.conv_cambio.setFrame(False)
        self.conv_cambio.setObjectName("conv_cambio")
        self.conv_inicial = QtWidgets.QComboBox(self.TelaConv)
        self.conv_inicial.setGeometry(QtCore.QRect(420, 340, 121, 22))
        self.conv_inicial.setEditable(False)
        self.conv_inicial.setFrame(False)
        self.conv_inicial.setObjectName("conv_inicial")
        self.ImagenPorco = QtWidgets.QLabel(self.TelaConv)
        self.ImagenPorco.setGeometry(QtCore.QRect(260, 50, 321, 231))
        self.ImagenPorco.setText("")
        self.ImagenPorco.setPixmap(QtGui.QPixmap(":/Icons and Images/Porco.svg"))
        self.ImagenPorco.setScaledContents(True)
        self.ImagenPorco.setObjectName("ImagenPorco")
        self.lbl_vale = QtWidgets.QLabel(self.TelaConv)
        self.lbl_vale.setGeometry(QtCore.QRect(345, 410, 61, 51))
        self.lbl_vale.setStyleSheet("font: 25 25pt \"Corbel Light\";\n"
"color: #4DC724;")
        self.lbl_vale.setObjectName("lbl_vale")
        self.lbl_valor_inicial = QtWidgets.QLabel(self.TelaConv)
        self.lbl_valor_inicial.setGeometry(QtCore.QRect(150, 390, 191, 81))
        self.lbl_valor_inicial.setStyleSheet("font: 25 35pt \"Corbel Light\";\n"
"color: rgb(162, 162, 162);")
        self.lbl_valor_inicial.setObjectName("lbl_valor_inicial")
        self.lbl_hoje = QtWidgets.QLabel(self.TelaConv)
        self.lbl_hoje.setGeometry(QtCore.QRect(670, 410, 71, 51))
        self.lbl_hoje.setStyleSheet("font: 25 25pt \"Corbel Light\";\n"
"color: #4DC724;")
        self.lbl_hoje.setObjectName("lbl_hoje")
        self.simbolo_cambio = QtWidgets.QLabel(self.TelaConv)
        self.simbolo_cambio.setGeometry(QtCore.QRect(410, 370, 71, 111))
        self.simbolo_cambio.setStyleSheet("font: 25 50pt \"Corbel Light\";\n"
"color: #A9ACF9;")
        self.simbolo_cambio.setObjectName("simbolo_cambio")
        self.lbl_valor_cambio = QtWidgets.QLabel(self.TelaConv)
        self.lbl_valor_cambio.setGeometry(QtCore.QRect(480, 390, 191, 81))
        self.lbl_valor_cambio.setStyleSheet("font: 25 35pt \"Corbel Light\";\n"
"color: rgb(162, 162, 162);")
        self.lbl_valor_cambio.setObjectName("lbl_valor_cambio")
        ConversorDeMoeda.setCentralWidget(self.TelaConv)

        self.retranslateUi(ConversorDeMoeda)
        QtCore.QMetaObject.connectSlotsByName(ConversorDeMoeda)

    def retranslateUi(self, ConversorDeMoeda):
        _translate = QtCore.QCoreApplication.translate
        ConversorDeMoeda.setWindowTitle(_translate("ConversorDeMoeda", "Convert Coin - Conversor de Moeda"))
        self.line_valor.setPlaceholderText(_translate("ConversorDeMoeda", "Valor"))
        self.simbolo_inicial.setText(_translate("ConversorDeMoeda", "R$"))
        self.lbl_de.setText(_translate("ConversorDeMoeda", "De"))
        self.lbl_para.setText(_translate("ConversorDeMoeda", "Para"))
        self.lbl_vale.setText(_translate("ConversorDeMoeda", "Vale"))
        self.lbl_valor_inicial.setText(_translate("ConversorDeMoeda", "0,000000"))
        self.lbl_hoje.setText(_translate("ConversorDeMoeda", "Hoje"))
        self.simbolo_cambio.setText(_translate("ConversorDeMoeda", "R$"))
        self.lbl_valor_cambio.setText(_translate("ConversorDeMoeda", "0,000000"))
from View.PY import ConQRC
